[project.scripts]
datascix = "datascix.__main__:main"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "datascix"
version = "1.0.0"

[tool.setuptools.packages.find]
where = ["src"]